### ISSUE TITLE
Move Adminhtml Menu "Development" under "System"

### ISSUE THREAD

**Issue by Vinai** [LimeSoda/LimeSoda_SampleDataGenerator#12]
Great extension, but having another top level menu entry really makes work harder on small resolutions.  
Why not add a record "Development" under System, or System > Tools, or Dashboard? Anything but another top level menu entry, please ;)
Thanks!

**Comment by mzeis** [comment]
Thanks for your suggestion!

We put it unter "Development" because we also have other development extensions.
We'll consider putting the SDG under System because we know it can be pain to have a lot of top level menu entries. On the other hand we want to avoid too many menu levels because it's also not fun if you have a 4 level hierarchy. :-)

**Comment by mzeis** [comment]
While I still agree with you I'll close this issue as I don't think there is a high demand for a change in this old extension. If somebody still wants to see this being moved I'm happy to accept a PR though. :-)
